# Generated by Django 5.1.4 on 2024-12-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_flow_app', '0002_alter_location_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='title',
            field=models.CharField(max_length=10000, unique=True),
        ),
    ]
