# Generated by Django 5.1.4 on 2024-12-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_flow_app', '0003_alter_location_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidents',
            name='type_inc',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
